version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: web
    ports:
      - "3000:80"
    links:
      - mysql
    volumes:
      - ../app:/app
  composer:
    image: composer
    volumes:
      - ../app:/app
    working_dir: /app
    command:
      - install
  mysql:
    image: mysql
    env_file:
      - mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "3001:8080"
    env_file:
      - adminer.env
    links:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "3002:80"
    env_file:
      - phpmyadmin.env
    links:
      - mysql
